### ISSUE TITLE
Peer to Peer code review 

### ISSUE THREAD

**Issue by MozamelJawad** [bhushan354/code_reviewing#2]
Great job so far, but please, there are some issues you need to know and pay attention to in your projects:

- For those elements that need the same design, you can add a class selector, which will help you to set the design easily and also will help you to change it later easily.
- You can use semantic elements for your layout, which will help you easily manage and be good for Google search engines.

**Comment by bhushan354** [comment]
Thanks sir for reviewing my code , I will make necessary changes in my code to meet the requirements suggested by you .
